# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=0, verbose_name='\u72b6\u6001')),
                ('title', models.CharField(max_length=64, verbose_name='\u6d88\u606f\u6807\u9898')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u6d88\u606f\u5185\u5bb9')),
                ('category', models.PositiveSmallIntegerField(default=0, verbose_name='\u6d88\u606f\u7c7b\u578b')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recv_user', models.IntegerField(blank=True, null=True, verbose_name='\u63a5\u6536\u8005')),
                ('send_user', models.IntegerField(blank=True, null=True, verbose_name='\u53d1\u9001\u8005')),
                ('readed', models.BooleanField(default=False, verbose_name='\u5df2\u8bfb')),
                ('status', models.IntegerField(default=0, verbose_name='\u8bb0\u5f55\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Message')),
            ],
        ),
    ]
